name: news_now
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  appwrite: ^14.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  permission_handler: ^11.4.0
  profanity_filter: ^2.0.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomeIcons
      fonts:
        - asset: assets/fonts/CustomeIcons.ttf
